# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IGPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('closing_ref', models.CharField(max_length=8)),
                ('closed_date', models.DateTimeField(verbose_name='date published')),
                ('opening_ref', models.CharField(max_length=8)),
                ('opening_date', models.DateTimeField(verbose_name='date published')),
                ('market', models.CharField(max_length=255)),
                ('period', models.CharField(max_length=8)),
                ('direction', models.CharField(max_length=4)),
                ('size', models.FloatField()),
                ('opening_price', models.FloatField()),
                ('closing_price', models.FloatField()),
                ('trade_ccy', models.CharField(max_length=3)),
                ('pl', models.FloatField()),
                ('funding', models.FloatField()),
                ('borrowing', models.FloatField()),
                ('dividends', models.FloatField()),
                ('lrprem', models.FloatField()),
                ('others', models.FloatField()),
                ('commccy', models.FloatField()),
                ('comm', models.FloatField()),
                ('total', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='IndividualCashTransactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('transaction_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='IndividualPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.FloatField()),
                ('commission', models.FloatField()),
                ('fun_fund', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('current_size', models.FloatField()),
                ('current_commission', models.FloatField()),
                ('current_funfund', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='individualpl',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfx.Member'),
        ),
        migrations.AddField(
            model_name='individualpl',
            name='opening_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfx.IGPL'),
        ),
        migrations.AddField(
            model_name='individualcashtransactions',
            name='member_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pfx.Member'),
        ),
    ]
