# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='individualpl',
            old_name='opening_ref',
            new_name='igpl',
        ),
    ]
