# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0004_auto_20160427_1824'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igpl',
            options={'verbose_name': 'IG Profit and Loss'},
        ),
    ]
