# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0005_auto_20160427_1830'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igpl',
            options={'verbose_name': 'IG Profit and Loss Entry', 'verbose_name_plural': 'IG Profit and Loss Entries'},
        ),
        migrations.AlterModelOptions(
            name='individualcash',
            options={'verbose_name': 'Individual Cash Entry', 'verbose_name_plural': 'Individual Cash Entries'},
        ),
        migrations.AlterModelOptions(
            name='individualpl',
            options={'verbose_name': 'Individual Profit and Loss Entry', 'verbose_name_plural': 'Individual Profit and Loss Entries'},
        ),
    ]
