# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0006_auto_20160427_1834'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='current_funfund',
            new_name='current_fun_fund',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='current_size',
            new_name='current_trade_size',
        ),
    ]
