# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 17:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0008_auto_20160427_1844'),
    ]

    operations = [
        migrations.RenameField(
            model_name='igpl',
            old_name='pl',
            new_name='gross_profit',
        ),
        migrations.RenameField(
            model_name='igpl',
            old_name='total',
            new_name='net_profit',
        ),
    ]
