# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 16:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0010_auto_20160428_1727'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='igpl',
            name='id',
        ),
        migrations.AlterField(
            model_name='igpl',
            name='closing_ref',
            field=models.CharField(max_length=8, primary_key=True, serialize=False),
        ),
    ]
