# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0012_auto_20160429_1136'),
    ]

    operations = [
        migrations.AddField(
            model_name='igpl',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='igpl',
            name='closing_ref',
            field=models.CharField(max_length=8),
        ),
    ]
