# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 10:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0014_auto_20160429_1138'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='user2',
            new_name='user',
        ),
    ]
