# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-29 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0018_auto_20160429_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='igpl',
            name='closing_ref',
            field=models.CharField(max_length=8, unique=True),
        ),
        migrations.AlterField(
            model_name='igpl',
            name='opening_ref',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
