# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-02 00:28
from __future__ import unicode_literals

from django.db import migrations, models
import pfx.models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0019_auto_20160429_1221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='individualpl',
            name='size',
        ),
        migrations.AddField(
            model_name='individualpl',
            name='profit',
            field=models.FloatField(),
        ),
    ]
