# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-03 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0022_auto_20160502_0225'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpl',
            name='size',
            field=models.FloatField(default=0),
        ),
    ]
