# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 12:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0023_individualpl_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='current_trade_size',
            new_name='manual_trade_size',
        ),
        migrations.AddField(
            model_name='member',
            name='automatic_trade_size',
            field=models.BooleanField(default=False),
        ),
    ]
