# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0024_auto_20160519_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='calculated_trade_size',
            field=models.FloatField(default=0),
        ),
    ]
