# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0025_member_calculated_trade_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.CharField(max_length=255, unique=True)),
                ('trade_datetime', models.DateTimeField()),
                ('market', models.CharField(max_length=255)),
                ('start_price', models.FloatField()),
                ('stop_price', models.FloatField()),
                ('target_price', models.FloatField()),
            ],
            options={
                'verbose_name': 'Trade Email',
                'verbose_name_plural': 'Trade Emails',
            },
        ),
    ]
