# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-23 11:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0026_tradeemail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradeemail',
            name='trade_datetime',
        ),
        migrations.AddField(
            model_name='tradeemail',
            name='time_live',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tradeemail',
            name='trade_date',
            field=models.CharField(default='', max_length=32),
            preserve_default=False,
        ),
    ]
