# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0027_auto_20160523_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='PositionViews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deal_id', models.CharField(max_length=255, unique=True)),
                ('show_all', models.BooleanField(default=False)),
            ],
        ),
    ]
