# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 13:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0028_positionviews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='positionviews',
            options={'verbose_name': 'Position View', 'verbose_name_plural': 'Position Views'},
        ),
    ]
