# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-05 13:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0029_auto_20160524_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='commission_received',
            field=models.FloatField(default=0.0),
        ),
    ]
