# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-10 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0031_auto_20160714_1804'),
    ]

    operations = [
        migrations.CreateModel(
            name='FunFundWithdrawl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('decription', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField(verbose_name='date published')),
            ],
            options={
                'verbose_name': 'Fun fund withdrawl',
                'verbose_name_plural': 'Fun fund withdrawls',
            },
        ),
    ]
