# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-09-11 16:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pfx', '0032_funfundwithdrawl'),
    ]

    operations = [
        migrations.AddField(
            model_name='individualpl',
            name='net_return',
            field=models.FloatField(default=0),
        ),
    ]
